### ISSUE TITLE
X-Pull Key not visible after upgrade to 4.7.5

### ISSUE THREAD

**Issue by foliovision** [foliovision/businesspress#18]
After I updated to WordPress 4.7.5, my X-Pull key doesn't show up anymore. We should probably also link to a page of documentation about where to find your X-Pull key and what it looks like.

![wordpress-47-update-resets-many-businesspress-preferences-including-killing-cdn-x-pull-key](https://user-images.githubusercontent.com/1180948/28389115-2c2dfa08-6cd5-11e7-809c-a0413fc41f22.png)

Even adding the key again and again doesn't work. I'm not sure if the key is stored but just not shown. We'll find out when KeyCDN gets banned by fail2ban.

**Comment by fvmartin** [comment]
Here was a bug in the options saving code. Fixed in #21 and BusinessPress 0.8.1 released and sites checked. I put in the missing X-Pull key.

The X-Pull key is user setting of the CDN pull zone on KeyCDN. I haven't found it's equivalent in StackPath. I guess different CDN providers have different mechanisms of verifying that the request comes from their servers. When we build BusinessPress documentation pages we should cover this there.
