### ISSUE TITLE
Make publishing of full-sized images in WordPress possible

### ISSUE THREAD

**Issue by foliovision** [foliovision/businesspress#32]
Since WordPress 5.3, WordPress by default prevents publishers from sharing images wider or taller than 2560px. This is a nuisance if you want to share full sized-images.

More here: https://foliovision.com/2021/11/full-size-images-wordpress

We should use `big_image_size_threshold` filter in BusinessPress to let users specify their desired max image size, like this:

![WP-Media-Settings-53-640x771](https://user-images.githubusercontent.com/1180948/142996761-89245f2d-436c-4439-b311-82816fc3740b.png)

Thanks!
Alec

**Comment by fvmartin** [comment]
Hello Alec,

I took care of this and added the setting here: https://github.com/foliovision/businesspress/commit/c453efe844ba395e68ccd85228628adc118be6e6

Please note that:

1) this WordPress routine is not applied to PNG images, see the reason here: 

- code: https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-admin/includes/image.php#L249
- ticket: #48736 Exclude PNG images from scaling after upload https://core.trac.wordpress.org/ticket/48736

2) the way it's done in WordPress core code does not let us add a separate field for Width and Height as it's a single value only - see here: https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-admin/includes/image.php#L273-L277

So here's what he have:

![businesspress-maximum-size](https://user-images.githubusercontent.com/1275725/142997491-9e42b821-9b00-4de1-ba45-aa7cd7f5944f.png)

There is the tooltip (the screenshot does show that) and the input field uses placeholder to show the value set by WordPress after applying all the filters. So you can see what your plugins or theme is forcing via the filter and we only store the value if you make it something else.

Thanks,
Martin
